### PR TITLE
Bump pulp-pypi-sync-job to v0.1.1 in stage

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/pulp-pypi-sync-job/issues/37

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... until available at https://quay.io/repository/thoth-station/pulp-pypi-sync-job?tab=tags

**Comment by fridex** [comment]
/unhold

The built image is available.

/assign @harshad16

**Review by harshad16 — APPROVED** [review]
lgtm
thanks :100:

**Pull request merged**
