### PR TITLE
Perform syncs of documents that are recent

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/document-sync-job/pull/15/

## Description

Let's sync only recent documents to reduce CPU time occupied by the job.

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... let's wait for the initial sync to complete.

**Comment by fridex** [comment]
The initial sync has been completed today to AWS prod:

```
2022-02-19 18:34:51,276   1 INFO     thoth.document_sync:124: Document 'solver-fedora-34-py39-220210070032-7b66a1c5ae0ae363' successfully copied to 's3://thoth-store/data/aws-prod/solver/solver-fedora-34-py39-220210070032-7b66a1c5ae0ae363'
2022-02-19 18:34:51,296   1 INFO     thoth.document_sync:221: Document sync job has finished successfully
```

We can do now syncs based on results computed in the past days now.

/unhold
/assign @harshad16

**Comment by harshad16** [comment]
amazing thanks for tracking this @fridex :100:

**Review by harshad16 — APPROVED** [review]
lgtm
thanks :100:

**Pull request merged**
