### PR TITLE
Don't ignore secret yamls

### PR DESCRIPTION
**Pull request by xtuchyna**
This is useless (and unnecessary pain) because we store the secret(s) inside the thoth-application

### CODE REVIEW

**Comment by harshad16** [comment]
we use [sops](https://github.com/mozilla/sops#sops-secrets-operations) for secrets creating with encryption, as a developer is creating the secret, the developer would need to first have the secret in the manifest file to run sops on it, we cant have secrets mistakenly pushed to the repo.
please close the pr.

**Comment by xtuchyna** [comment]
aight got it

**Comment by xtuchyna** [comment]
@harshad16 so shouldn't we have this mentioned in readme then?

**Comment by harshad16** [comment]
@xtuchyna yes, we should. please feel free to open a PR with readme update

**Pull request closed without merging**
