### PR TITLE
Bumped kebechet to 1.05

### PR DESCRIPTION
**Pull request by saisankargochhayat**
## Related Issues and Dependencies
Bump kebechet 
Depends on https://github.com/thoth-station/kebechet/pull/538

### CODE REVIEW

**Comment by fridex** [comment]
Any reason to hold more? The container image is available on quay:

https://quay.io/repository/thoth-station/kebechet-job?tab=tags

**Comment by harshad16** [comment]
> Any reason to hold more? The container image is available on quay:
> 
> https://quay.io/repository/thoth-station/kebechet-job?tab=tags

i wasn't aware we were building image of kebechet directly through quay.

**Comment by fridex** [comment]
> > Any reason to hold more? The container image is available on quay:
> > https://quay.io/repository/thoth-station/kebechet-job?tab=tags
> 
> i wasn't aware we were building image of kebechet directly through quay.

Ah, sorry. Forgot to notify you. I have configured a build trigger on quay when a push to master is done (tagged creates a new release).

**Pull request merged**
