### PR TITLE
Change solver virtual env location

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Depends-On: https://github.com/thoth-station/solver/pull/662
Related: https://github.com/thoth-station/solver/issues/417
Related: https://github.com/thoth-station/s2i-thoth/issues/128

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
CC @harshad16 this will be needed once we push new s2i-thoth based solvers

**Comment by harshad16** [comment]
I will merge this as soon as I get in the s2i based solver released.

**Comment by fridex** [comment]
> I will merge this as soon as I get in the s2i based solver released.

Awesome, thanks! :+1:

**Comment by fridex** [comment]
@harshad16 maybe this PR is related to solver issues in test?

**Review by harshad16 — APPROVED** [review]

**Pull request merged**
