### PR TITLE
Resubmit pending pods in Amun inspections

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
@KPostOffice we use `steps` and not dag here, not sure if the configuration option applies here as well.

**Comment by KPostOffice** [comment]
> @KPostOffice we use `steps` and not dag here, not sure if the configuration option applies here as well.

It does. I still don't think it was implemented properly yet, I can link the discussion/PR from Argo if you want

**Comment by fridex** [comment]
> > @KPostOffice we use `steps` and not dag here, not sure if the configuration option applies here as well.
> 
> It does. I still don't think it was implemented properly yet, I can link the discussion/PR from Argo if you want

It does not look like this configuration is propagated correctly when applying this configuration to the cluster. When I adjust the template, this configuration option is not shown in the workflows created (si correctly states it in the workflow though).

**Pull request merged**
