### PR TITLE
Bump Amun API to v0.9.5 in stage environment

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/amun-api/issues/626

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... until a new release is done:

https://quay.io/repository/thoth-station/amun-api?tab=tags

**Comment by goern** [comment]
the delivery of the new image seems to hang somewhere?!

/assign @harshad16

**Comment by harshad16** [comment]
> the delivery of the new image seems to hang somewhere?!
> 

yes I m working on it, sorry for the delay.

**Pull request merged**
