### PR TITLE
Bump management-api to v0.14.0 in prod

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/thoth-application/pull/953
Related: #949

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
lgtm, thanks
let get this in, however let keep the bump of prod and stage separate for future iterations.

**Comment by fridex** [comment]
/approve

> lgtm, thanks
> let get this in, however let keep the bump of prod and stage separate for future iterations.

Thanks, will do :+1:

**Pull request merged**
