### PR TITLE
Remove variable not required

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/thoth-application/issues/408

## This introduces a breaking change

- [ ] Yes
- [x] No

## Test or Stage Environment

- [x] Pull Requests added content to STAGE environment

## This Pull Request implements

Remove variable not required

### CODE REVIEW

**Comment by harshad16** [comment]
can you please review these:

- https://github.com/thoth-station/thoth-application/blob/68bac5cc768632b9d2f846619b6191e1e89da939/core/overlays/test/configmaps.yaml#L34
- https://github.com/thoth-station/thoth-application/blob/68bac5cc768632b9d2f846619b6191e1e89da939/advise-reporter/base/cronjob.yaml#L87
- https://github.com/thoth-station/thoth-application/blob/68bac5cc768632b9d2f846619b6191e1e89da939/advise-reporter/base/deploymentconfig.yaml#L53
- https://github.com/thoth-station/thoth-application/blob/68bac5cc768632b9d2f846619b6191e1e89da939/slo-reporter/base/cronjob.yaml#L75

i m a bit confused, when do we use this variable and when not.
can you please help me understand.

**Comment by pacospace** [comment]
> can you please review these:
> 
> * https://github.com/thoth-station/thoth-application/blob/68bac5cc768632b9d2f846619b6191e1e89da939/core/overlays/test/configmaps.yaml#L34

For this specific case, it was not required, see comment here: https://github.com/thoth-station/thoth-application/issues/408#issuecomment-691864455

> * https://github.com/thoth-station/thoth-application/blob/68bac5cc768632b9d2f846619b6191e1e89da939/advise-reporter/base/cronjob.yaml#L87

connect to public Ceph: https://github.com/thoth-station/advise-reporter/blob/b689e66832e1a42aa20f67b8af263b9176441c8c/thoth/advise_reporter/advise_reporter.py#L113

> * https://github.com/thoth-station/thoth-application/blob/68bac5cc768632b9d2f846619b6191e1e89da939/advise-reporter/base/deploymentconfig.yaml#L53

As we recently moved consumer logic to investigator, there will be no more deployment. I will remove the part :) Thanks for pointing this out

> * https://github.com/thoth-station/thoth-application/blob/68bac5cc768632b9d2f846619b6191e1e89da939/slo-reporter/base/cronjob.yaml#L75

Connect to public Ceph: https://github.com/thoth-station/slo-reporter/blob/8c26d7337ba090a7fc7cf507ea3569ce3023583a/app.py#L143


> 
> i m a bit confused, when do we use this variable and when not.
> can you please help me understand.

Sure no problem :) 

For the rest of the cases, that specific env variable is required by components that store on public Ceph which is where we store csv file to be used in Hue/Superset. See links above.

**Comment by harshad16** [comment]
ah i see, thanks for the update.

**Review by harshad16 — APPROVED** [review]
lgtm
thanks for the fix :100:

**Pull request merged**
