### PR TITLE
Deploy user-api v0.25.2 to stage environment

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/user-api/pull/1423

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... until the built image is available

**Comment by fridex** [comment]
/unhold

... the image is available https://quay.io/repository/thoth-station/user-api?tab=tags

**Review by harshad16 — APPROVED** [review]
lgtm, thanks :100: 
/approve

**Pull request merged**
