### PR TITLE
Bump user-api to v0.11.1 in stage environments

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/user-api/issues/1202

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/hold

https://github.com/thoth-station/user-api/issues/1202
https://quay.io/repository/thoth-station/user-api?tab=tags

**Comment by fridex** [comment]
/unhold

ready.

**Comment by harshad16** [comment]
once we update the deploymentconfig of user-api , based on the new changes of messaging we can go ahead with this one.
as v0.11.1 is using thoth-messaging v0.10.1 which requires different env vars.

**Comment by fridex** [comment]
> once we update the deploymentconfig of user-api , based on the new changes of messaging we can go ahead with this one.
> as v0.11.1 is using thoth-messaging v0.10.1 which requires different env vars.

CC: @KPostOffice could you point me to changes that are needed so we can propagate this one?

**Comment by harshad16** [comment]
>  could you point me to changes that are needed so we can propagate this one?
The test/deploymentconfig is to be moved to the base/deploymentconfig

**Comment by fridex** [comment]
> > could you point me to changes that are needed so we can propagate this one?
> 
> The test/deploymentconfig is to be moved to the base/deploymentconfig

Thanks, added in https://github.com/thoth-station/thoth-application/pull/767

**Comment by harshad16** [comment]
/unhold 
#767

**Review by harshad16 — APPROVED** [review]
lgtm, thanks :100:

**Comment by fridex** [comment]
@harshad16 thanks! :eyes:

**Pull request merged**
