### PR TITLE
Bump adviser to v0.55.0 in stage environment

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/prescriptions/pull/23487

### CODE REVIEW

**Comment by mayaCostantini** [comment]
Thanks 💯
/approve

**Comment by mayaCostantini** [comment]
@fridex I don't think the v0.55.0 has been released yet

**Comment by fridex** [comment]
> @fridex I don't think the v0.55.0 has been released yet

I was waiting for prescriptions, but merged manually (v0.19.0). Adviser new release triggered in https://github.com/thoth-station/adviser/issues/2339 👍🏻

**Comment by fridex** [comment]
The built image is available. 🚀

**Pull request merged**
