### PR TITLE
Bump investigator to v0.8.2 in stage environments

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

Related: https://github.com/thoth-station/thoth-application/pull/743

### CODE REVIEW

**Comment by fridex** [comment]
ready, see https://quay.io/repository/thoth-station/investigator?tab=tags

**Review by harshad16 — COMMENTED** [review]
may be we should test it first in test cluster.

**Comment by pacospace** [comment]
> ready, see https://quay.io/repository/thoth-station/investigator?tab=tags

lgtm, do we want to try investigator in test first?

**Comment by fridex** [comment]
Yes, want to give it a try shortly. Thanks!

**Review by harshad16 — APPROVED** [review]
Thanks

**Pull request merged**
