### PR TITLE
Move solver from test to base

### PR DESCRIPTION
**Pull request by bissenbay**
@harshad16 We have checked a new change in logic where we introduced `parse-solver-output` and looks to be good:
```
Name:                solver-rhel-8-py36-b57922dd
Namespace:           thoth-test-core
ServiceAccount:      argo
Status:              Succeeded
Conditions:          
 Completed           True
Created:             Wed Sep 30 12:58:03 -0400 (1 minute ago)
Started:             Wed Sep 30 12:58:03 -0400 (1 minute ago)
Finished:            Wed Sep 30 12:59:19 -0400 (now)
Duration:            1 minute 16 seconds
ResourcesDuration:   1m29s*(1 cpu),6m38s*(100Mi memory)
Parameters:          
  ceph_bucket_prefix: data
  ceph_bucket_name:  thoth
  ceph_host:         s3.upshift.redhat.com
  deployment_name:   ocp-test
  THOTH_SOLVER_NAME: solver-rhel-8-py36
  THOTH_SOLVER_WORKFLOW_ID: solver-rhel-8-py36-b57922dd
  THOTH_LOG_SOLVER:  DEBUG
  THOTH_SOLVER_NO_TRANSITIVE: 1
  THOTH_SOLVER_PACKAGES: numpy===1.14.0
  THOTH_SOLVER_INDEXES: https://pypi.org/simple
  THOTH_FORCE_SYNC:  0

STEP                            TEMPLATE                                 PODNAME                                 DURATION  MESSAGE
 ✔ solver-rhel-8-py36-b57922dd  solve-and-sync                                                                               
 ├-✔ solverany(0)               solver-any/solve                         solver-rhel-8-py36-b57922dd-3346182458  17s         
 ├-✔ graph-sync-solverany(0)    graph-sync/graph-sync                    solver-rhel-8-py36-b57922dd-2959581393  19s         
 ├-✔ parse-solver-output        parse-solver-output/parse-solver-output  solver-rhel-8-py36-b57922dd-876798533   18s         
 └-✔ send-messages-to-be-sent   send-messages/send-messages              solver-rhel-8-py36-b57922dd-2100818870  15s 
```
This PR is meant to move from `test` to `base`, could you please @harshad16 take a closer look, so I don't screw up :smile: , thanks!

### CODE REVIEW

**Review by pacospace — COMMENTED** [review]
Very nice work!! :100 I think also workflow-helper version need to go to stage, you need to update it in core/base/stage/imagestreamtags.yaml

**Review by harshad16 — COMMENTED** [review]
This looks good to me.
Thanks.

just update the images in the core, as @pacospace  suggested.

**Comment by bissenbay** [comment]
> Very nice work!! :100 I think also workflow-helper version need to go to stage, you need to update it in core/base/stage/imagestreamtags.yaml

Only in `stage`, or `test` as well?

**Comment by pacospace** [comment]
> > Very nice work!! :100 I think also workflow-helper version need to go to stage, you need to update it in core/base/stage/imagestreamtags.yaml
> 
> Thanks, only in `stage`, or in `test` as well?

test is always updated automatically by Argo CD. Human takes care of stage and prod :D :robot:

**Comment by bissenbay** [comment]
> This looks good to me.
> Thanks.
> 
> just update the images in the core, as @pacospace suggested.

I checked and it is up-to-date with the latest release on Quay.

**Comment by pacospace** [comment]
then let's do it!!

**Review by pacospace — APPROVED** [review]

**Pull request merged**
