### PR TITLE
Bumped graph sync job

### PR DESCRIPTION
**Pull request by saisankargochhayat**
## Related Issues and Dependencies
Bumped graph-sync

### CODE REVIEW

**Comment by pacospace** [comment]
image tag is not on quay yet: https://quay.io/repository/thoth-station/graph-sync-job?tag=latest&tab=tags

**Review by harshad16 — COMMENTED** [review]
lgtm, 
https://quay.io/repository/thoth-station/graph-sync-job?tab=tags image is now available

**Review by harshad16 — APPROVED** [review]

**Pull request merged**
