### PR TITLE
make cve-update kafka producer

### PR DESCRIPTION
**Pull request by bissenbay**
To test changes we made in https://github.com/thoth-station/cve-update-job/pull/374

Related-To: https://github.com/thoth-station/cve-update-job/issues/373

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
lgtm :+1:

**Review by KPostOffice — COMMENTED** [review]
Looks good, please just set the following env var:
```
KAFKA_TOPIC_CONSUMER_ENABLE_AUTO_COMMIT=False
```

**Comment by bissenbay** [comment]
> Looks good, please just set the following env var:
> 
> ```
> KAFKA_TOPIC_CONSUMER_ENABLE_AUTO_COMMIT=False
> ```

thanks, but look like it's `KAFKA_CONSUMER_ENABLE_AUTOCOMMIT` from https://github.com/thoth-station/investigator, which spelling is correct?

**Comment by KPostOffice** [comment]
> > Looks good, please just set the following env var:
> > ```
> > KAFKA_TOPIC_CONSUMER_ENABLE_AUTO_COMMIT=False
> > ```
> 
> thanks, but look like it's `KAFKA_CONSUMER_ENABLE_AUTOCOMMIT` from https://github.com/thoth-station/investigator, which spelling is correct?

https://github.com/thoth-station/messaging/blob/31da1b329ca95580e15d8fef7c27109b16defaf1/thoth/messaging/config.py#L44-L48

See here, there are two instances of similar configuration

**Comment by bissenbay** [comment]
@KPostOffice thanks, PTAL https://github.com/thoth-station/thoth-application/pull/593/commits/23063a5b1726330c4315b393e93668a949fd6fbd

**Comment by bissenbay** [comment]
@harshad16 can we test it?

**Comment by harshad16** [comment]
> @harshad16 can we test it?

sure, if the wip is over, we can.
can we remove the wip from the pr?

**Review by KPostOffice — APPROVED** [review]

**Pull request merged**
