### PR TITLE
Extend provenance checker workflow with new steps

### PR DESCRIPTION
**Pull request by pacospace**
## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/thoth-application/issues/818

## This introduces a breaking change

- [ ] Yes
- [x] No

## Test or Stage Environment

- [x] Pull Requests added content to STAGE environment
- [ ] Pull Requests to `AICoE/aicoe-cd` has been opened:

### CODE REVIEW

**Comment by harshad16** [comment]
workflow-helpers v0.4.1 is available.

**Comment by pacospace** [comment]
> workflow-helpers v0.4.1 is available.

Thanks Harshad, I realized before the feature was added to support @fridex with user-api testing, I still need review for: https://github.com/thoth-station/workflow-helpers/pull/203 and new release

**Comment by pacospace** [comment]
> > workflow-helpers v0.4.1 is available.
> 
> Thanks Harshad, I released before the feature was added to support @fridex with user-api testing, I still need review for: [thoth-station/workflow-helpers#203](https://github.com/thoth-station/workflow-helpers/pull/203) and new release

v0.5.0 is the correct one

**Comment by pacospace** [comment]
I tested in test environment:

```
STEP                                                 TEMPLATE                                                         PODNAME                                                      DURATION  MESSAGE
 ✔ provenance-checker-210202075859-fc13440741027d96  provenance-checker                                                                                                                        
 ├-✔ provenance-check                                provenance-check/provenance-check                                provenance-checker-210202075859-fc13440741027d96-2972724932  12s         
 ├-✔ graph-sync-provenance-check(0)                  graph-sync/graph-sync                                            provenance-checker-210202075859-fc13440741027d96-13043846    15s         
 ├-✔ parse-provenance-checker-output                 parse-provenance-checker-output/parse-provenance-checker-output  provenance-checker-210202075859-fc13440741027d96-1081904809  35s         
 └-✔ send-messages                                   send-messages/send-messages                                      provenance-checker-210202075859-fc13440741027d96-3271041339  18s     
```

**Comment by pacospace** [comment]
I all the image required for workflow helper.

This change affects also cnv-prod, do we want to proceed adding also workflow-helpers image to cnv-prod imagestream tag so that we can have this feature in already? @goern @harshad16 @fridex

**Comment by harshad16** [comment]
> This change affects also cnv-prod, do we want to proceed adding also workflow-helpers image to cnv-prod imagestream tag so that we can have this feature in already? 

I would ask the question if this is tested in the test environment?
I don't think it would break prod, as I see addition and no removal, also all base images are available(if not the same version).

anyhow if you feel it would break the prod, it is always best to be safe and add the changes in the respective overlays.

**Comment by pacospace** [comment]
> > This change affects also cnv-prod, do we want to proceed adding also workflow-helpers image to cnv-prod imagestream tag so that we can have this feature in already?
> 
> I would ask the question if this is tested in the test environment?

Yes you can see comment above :)
> I don't think it would break prod, as I see addition and no removal, also all base images are available(if not the same version).
> 

 I don't expect breaks as in stage we changed messaging version of components without issues, therefore I think we can proceed and have the new workflow helpers in prod as well. 

> anyhow if you feel it would break the prod, it is always best to be safe and add the changes in the respective overlays.

**Comment by harshad16** [comment]
@pacospace thanks for the testing :)
can you add the update of image for prod, as a separate commit in this pr.

**Pull request merged**
