### PR TITLE
suspend all data ingestion producers

### PR DESCRIPTION
**Pull request by harshad16**
suspend all data ingestion producers
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

## Related Issues and Dependencies

Related-to: #797

### CODE REVIEW

**Comment by goern** [comment]
This PR change can be reverted if we have updated argo-workflow?

/question

**Review by pacospace — APPROVED** [review]
Thanks!

**Comment by harshad16** [comment]
> This PR change can be reverted if we have updated argo-workflow?

lets first test it manually, we can do that via creating job out of the cronjobs
if everything seems correct, we can revert back later with new pr.

**Pull request merged**
