### PR TITLE
reduce parallelism to 6

### PR DESCRIPTION
**Pull request by KPostOffice**
I tried changing this value to 6 manually but it didn't seem to change the number being run so I'm trying here instead.

### CODE REVIEW

**Comment by goern** [comment]
> I tried changing this value to 6 manually but it didn't seem to change the number being run so I'm trying here instead.
> 
> 

I think you need to restart the workflow controller pod after changing the config map

**Comment by pacospace** [comment]
> > I tried changing this value to 6 manually but it didn't seem to change the number being run so I'm trying here instead.
> 
> I think you need to restart the workflow controller pod after changing the config map

it should be updated automatically actually :) the controller checks for changes in that configmap periodically and put the state in sync :D

**Comment by goern** [comment]
The pre-commit Check needs to pass...

**Comment by KPostOffice** [comment]
@goern 
http://tekton-dashboard-tekton-pipelines.apps.thoth01.lab.upshift.rdu2.redhat.com/#/namespaces/thoth-ci/pipelineruns/aicoe-pipelinerun-5jv9k

**Comment by harshad16** [comment]
> @goern
> http://tekton-dashboard-tekton-pipelines.apps.thoth01.lab.upshift.rdu2.redhat.com/#/namespaces/thoth-ci/pipelineruns/aicoe-pipelinerun-5jv9k

seems to be a flask failure in API request

**Pull request merged**
