### PR TITLE
Bump User API to v0.8.0 in stage

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/user-api/pull/1138

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... until a new release is available and until we do not have the container image built.

**Comment by fridex** [comment]
https://github.com/thoth-station/user-api/pull/1138
https://quay.io/repository/thoth-station/user-api?tab=tags

**Comment by fridex** [comment]
... also, I'll test the functionality in testenv before unholding this.

**Comment by fridex** [comment]
/unhold
/assign @harshad16 

Looks operational in thoth-test-core.

**Review by harshad16 — APPROVED** [review]
lgtm :+1:

**Pull request merged**
