### PR TITLE
Qebhwt use send messages

### LINKED ISSUE #511: qeb-hwt workflow sending AdviserTrigger message [5pt]
As Thoth is moving to Kafka based components with investigator handling messages,

qeb-hwt workflow should send AdviserTrigger message so that thoth-investigator can schedule adviser.

### PR DESCRIPTION
**Pull request by saisankargochhayat**
## Related Issues and Dependencies
Closes #511 
Depended on - https://github.com/thoth-station/workflow-helpers/releases/tag/v0.1.16

### CODE REVIEW

**Comment by saisankargochhayat** [comment]
How do we control which version of workflow-helpers the qeb-hwt workflow uses?

**Comment by pacospace** [comment]
> How do we control which version of workflow-helpers the qeb-hwt workflow uses?

that version is placed in core repo because used by many thoth-applications

**Review by pacospace — COMMENTED** [review]
Shall we put templates in overlays/test first for testing?

**Comment by saisankargochhayat** [comment]
> Shall we put templates in overlays/test first for testing?

Is there a qeb-hwt webhook receiver in test? Also should I just make a new folder ocp/test and copy over things from base and revert base back it what it was?

**Comment by pacospace** [comment]
> > Shall we put templates in overlays/test first for testing?
> 
> Is there a qeb-hwt webhook receiver in test? 
nope we always have one in prod only and all environments point to that at the moment. you need to test sending messages now, so as far as the message in Kafdrop rest should happen as before.

> Also should I just make a new folder ocp/test and copy over things from base and revert base back it what it was?
ocp is already an overlays, in this case not sure what is best! @harshad16 will know :)

**Comment by harshad16** [comment]
From this discussion and previous discussion, it feels like, qebhwt is to be present in the thoth namespace rather being in bots namespace, we should have overlays stage, test, and deploy the receiver in the namespace respectively and so that we have flow while developing.

**Comment by goern** [comment]
damned bots...

/label hacktoberfest-accepted

**Comment by saisankargochhayat** [comment]
Thanks, I have moved the new templates to the test directory

**Review by pacospace — APPROVED** [review]
/lgtm

**Comment by harshad16** [comment]
missing the kustomize update of the changes in this place,https://github.com/thoth-station/thoth-application/blob/96be7cb5bae9ab9b1f369544f89331c3b7750cb5/qeb-hwt-github-app/overlays/test/kustomization.yaml#L10

**Pull request merged**
