### PR TITLE
Bump SLO reporter in prod and change email recipient in stage

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

Bump SLO reporter in prod to v0.8.2

change email recipient in stage to go to thoth-aicoe team

Related-To: https://github.com/thoth-station/thoth-application/issues/817

### CODE REVIEW

**Comment by pacospace** [comment]
cc @harshad16 I miss thanos endpoint for slo-reporter CM. Morevoer the secret for Thanos endpoint in the prod deployment is not the correct one, I think it is the same as the stage one.

**Comment by pacospace** [comment]
> cc @harshad16 I miss `Thanos endpoint` for slo-reporter CM for prod. Morevoer, the `secret for Thanos endpoint` in the prod deployment is not the correct one, I think it is the same as the stage one.

Tested locally and no problem in using `http://prometheus-portal-thoth-infra-prod.apps.cnv.massopen.cloud/`

**Review by harshad16 — APPROVED** [review]
LGTM, thanks for the check

**Pull request merged**
