### PR TITLE
WIP: Use prepared data from Ceph do not propagate large data in env vars

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/thoth-application/issues/902
- [x] Related: https://github.com/thoth-station/common/pull/1109
- [x] Related: https://github.com/thoth-station/adviser/pull/1670
- [x] Related: https://github.com/thoth-station/management-api/pull/705
- [ ] Related: https://github.com/thoth-station/investigator/pull/445
- [x] Related: https://github.com/thoth-station/user-api/pull/1259
- [x] Related: https://github.com/thoth-station/storages/pull/2221
- [x] Related: https://github.com/thoth-station/management-api/pull/707
- [x] Related: https://github.com/thoth-station/messaging/pull/359

## This introduces a breaking change

- [x] Yes

As this is a breaking change, I'm not sure if we want to adjust directly base templates for all the deployments since this will require updating adviser in all deployments. We can probably start with the test environment (copy the templates there) and start rolling to stage and prod subsequently.

CC @harshad16 @pacospace wdyt?

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
which version of adviser support these changes?

**Comment by fridex** [comment]
> which version of adviser support these changes?

Not release yet. The linked PRs need to go in first (with corresponding releases).

**Comment by fridex** [comment]
> Earlier missed to see the question in the description.
> so as we want to test this in test,
> we need to move all these changes to test overlay.
> 
> simple method, copy over the both sub directories to test overlay.
> then add them to patchstrategymerge.
> that should do the trick

OK, so let's do it in a non-destrictive way. Let's keep the message data in the messages for now and at the same time let's configure adviser to *optionally* provide prepared data. If a flag is turned on, it will fallback to the legacy version so we do not break the system. Also, let's include your suggested change in the manifests. I'll adjust PRs accordingly tomorrow. This way we can fallback to old implementation if anything goes wrong.

**Comment by fridex** [comment]
Replaced with https://github.com/thoth-station/thoth-application/pull/982

**Pull request closed without merging**
