### PR TITLE
bump version of Adviser v0.33.1 in stage

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... until available at https://quay.io/repository/thoth-station/adviser?tab=tags

**Comment by fridex** [comment]
> @fridex: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> aicoe-ci/prow/kustomize-build	[31f5749](https://github.com/thoth-station/thoth-application/commit/31f57494e3f1eb99beb1ca89a923fe0a33ee6336)	[link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/prow-logs/pr-logs/pull/thoth-station_thoth-application/1659/kustomize-build/1403256645739352064)	`/test kustomize-build`
> [Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=1659). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

CC @goern @harshad16

**Comment by goern** [comment]
thats related to https://github.com/thoth-station/thoth-application/commit/d3875c67d953c138c4ef4d77a9899c9d8bac4f71

@tumido  ?

**Comment by goern** [comment]
I have rolled back to v0.3.2 of opf-toolbox

**Pull request merged**
