### PR TITLE
Bump adviser version to 0.17.0 in stage

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/adviser/issues/1226
Fixes: https://github.com/thoth-station/thoth-application/issues/445

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... until available in https://quay.io/repository/thoth-station/adviser?tab=tags

**Comment by fridex** [comment]
/unblock
/assign @harshad16 

the container image is available

**Review by harshad16 — APPROVED** [review]
Thanks :100:

**Pull request merged**
