### PR TITLE
Bump Kebechet to v1.3.0 in prod

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/thoth-application/pull/1532
Related: https://github.com/thoth-station/kebechet/issues/730

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... until the built image is available.

**Comment by fridex** [comment]
CC @KPostOffice changes related to thoth-sourcemanagement changes will go prod

**Comment by fridex** [comment]
/unhold
the image is available https://quay.io/repository/thoth-station/kebechet-job?tab=tags

/assign @KPostOffice 
/assign @harshad16

**Comment by harshad16** [comment]
/approve
thanks :100:

**Pull request merged**
