### PR TITLE
Bump user-api to v0.34.4 in stage environment

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
/hold


... testing changes in the test environment.

**Review by harshad16 — APPROVED** [review]
/unhold
/lgtm
/approve
thanks :100:

**Comment by fridex** [comment]
Sadly, will not work - see https://github.com/thoth-station/user-api/issues/1645#issuecomment-1031857876

/close

**Comment by fridex** [comment]
Actually, we could have this in if deployment configuration is adjusted - see https://github.com/thoth-station/thoth-application/pull/2330

/reopen

**Pull request merged**
