### PR TITLE
Bump graph related component to v0.51.0 of thoth-storages

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Related-To: https://github.com/thoth-station/thoth-application/issues/1792 (all patch releases)

### CODE REVIEW

**Review by fridex — APPROVED** [review]
lgmt 👍🏻 

/hold

haven't checked if images are available, free feel to unhold this if this can go in

**Comment by pacospace** [comment]
> lgmt 👍🏻
> 
> /hold
> 
> haven't checked if images are available, free feel to unhold this if this can go in

They are all ready on quay :)

**Pull request merged**
