### PR TITLE
Supply prescription.yaml to adviser container

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

Related: https://github.com/thoth-station/thoth-application/issues/1052

### CODE REVIEW

**Comment by fridex** [comment]
/hold

This requires adviser with the prescription feature available and `prescription.yaml` available on Ceph (needs at least one run of prescription-sync job).

**Review by harshad16 — APPROVED** [review]
/unhold
/approve

prescription-sync job is now available in all clusters.

**Pull request merged**
