### PR TITLE
:face_in_clouds: Remove unused env var in graph-sync job

### PR DESCRIPTION
**Pull request by harshad16**
Remove unused env var in graph-sync job
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

## Related Issues and Dependencies

Related-to: https://github.com/thoth-station/graph-sync-job/pull/678

### CODE REVIEW

**Comment by codificat** [comment]
Should this also be removed from the job openshift template? https://github.com/thoth-station/thoth-application/blob/951f33db6f125803794e7d9812b1deffb7ed09db/graph-sync/base/openshift-templates/syncJob-template.yaml#L123-L127

**Comment by harshad16** [comment]
> Should this also be removed from the job openshift template?
> 
> https://github.com/thoth-station/thoth-application/blob/951f33db6f125803794e7d9812b1deffb7ed09db/graph-sync/base/openshift-templates/syncJob-template.yaml#L123-L127

yes, as removed in the pr

**Pull request merged**
