### PR TITLE
Bumped kebechet to 1.0.7

### PR DESCRIPTION
**Pull request by saisankargochhayat**
## Related Issues and Dependencies
Depends on - https://github.com/thoth-station/kebechet/pull/557

### CODE REVIEW

**Comment by saisankargochhayat** [comment]
I guess we can unhold and check

**Comment by fridex** [comment]
> I guess we can unhold and check

Yes, the image is available:

https://quay.io/repository/thoth-station/kebechet-job?tab=tags

**Review by fridex — APPROVED** [review]

**Pull request merged**
