### PR TITLE
Fix Grafana dashboards in prod

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Review by harshad16 — CHANGES_REQUESTED** [review]
lgtm
thanks for this changes.
a small change is needed, each dashboard has a version at the bottom
can you increment it (+1) for this changes
https://github.com/thoth-station/thoth-application/blob/91e1047c620493d884d745a84207e57ad16cb424/grafana-dashboard/overlays/aws-prod/thoth-kafka-argo-metrics.json#L1794
so that we can do the same in argocd to pull the changes in.

**Comment by pacospace** [comment]
> 

Yes of course :) thanks @harshad16 !

**Review by harshad16 — CHANGES_REQUESTED** [review]
Require version updates for all dashboards that are changed in this PR.
missing the version update in few of them

**Comment by pacospace** [comment]
> Require version updates for all dashboards that are changed in this PR. missing the version update in few of them

Sorry my error, they should be all updated now :)

**Review by harshad16 — APPROVED** [review]
lgtm
thanks :100:

**Pull request merged**
