### PR TITLE
Bump solvers to v1.9.0 in stage environment

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/solver/issues/708

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... until available at https://quay.io/repository/thoth-station/solver-rhel-8-py36?tab=tags

**Comment by harshad16** [comment]
i will take care of this, there issue with costume images like solver.
will try to get this merged by end of the day.

**Comment by fridex** [comment]
> i will take care of this, there issue with costume images like solver.
> will try to get this merged by end of the day.

No rush, I need to manually test the OOM handling. It can wait. Thanks 👍🏻

**Comment by fridex** [comment]
> > i will take care of this, there issue with costume images like solver.
> > will try to get this merged by end of the day.
> 
> No rush, I need to manually test the OOM handling. It can wait. Thanks 👍🏻

Oh, but I will need container images built :) But that can wait based on your priorities. 🐈

**Comment by harshad16** [comment]
> Oh, but I will need container images built :) But that can wait based on your priorities.

That was the issue, I will fix it by eot , it would be available tomorrow for your testing. :+1:

**Comment by harshad16** [comment]
Fixed it, the image is available.
/approve

**Comment by fridex** [comment]
@harshad16 thanks, looks like it works, let's see how changes will behave in the cluster 👍🏻

**Pull request merged**
