### PR TITLE
Bump graph-sync-job to v0.10.18 in stage environment

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/graph-sync-job/issues/634

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... until available at https://quay.io/repository/thoth-station/graph-sync-job?tab=tags

**Comment by fridex** [comment]
The image is available.

/assign @harshad16
PTAL

**Review by harshad16 — APPROVED** [review]
lgtm
thanks :100:

**Pull request merged**
