### PR TITLE
Run graph-sync in advises only when authenticated

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
I renamed "privileged" to "authenticated" that might better describe the scenario.

**Comment by pacospace** [comment]
is this similar PR for https://github.com/thoth-station/thoth-application/pull/1130?

**Comment by KPostOffice** [comment]
@pacospace Yeah, they are both attempting to do the same thing. I like this approach better. I will close my PR

**Review by KPostOffice — APPROVED** [review]

**Review by harshad16 — APPROVED** [review]
lgtm :+1:

**Pull request merged**
