### PR TITLE
Bump user-api to v0.29.1 in stage

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/user-api/pull/1535

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... until available

**Comment by fridex** [comment]
> /hold
> 
> ... until available https://quay.io/repository/thoth-station/user-api?tab=tags

The built image is available.

/assign @harshad16

**Review by harshad16 — APPROVED** [review]
lgtm
thanks :100:

**Pull request merged**
