### PR TITLE
Use solver in version 1.6.1 in stage environment

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/solver/pull/608 https://github.com/thoth-station/solver/issues/611

### CODE REVIEW

**Comment by fridex** [comment]
/hold

until the new release won't be available on https://quay.io/repository/thoth-station/solver-fedora-32-py37?tab=tags

**Comment by fridex** [comment]
ready to be :ship:

**Review by pacospace — APPROVED** [review]
Nice!!! :100:

**Pull request merged**
