### PR TITLE
:sleeping: Turn off sentry logging by removing sentry_dsn

### PR DESCRIPTION
**Pull request by harshad16**
:sleeping: Turn off sentry logging by removing sentry_dsn
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

## Description

As part of the hibernation of the project.

### CODE REVIEW

**Comment by goern** [comment]
as `sentry_dsn` is removed from the secrets, it will not be injected as an env var in deployments, and therefore thoth.logging will not send to sentry. correct?

**Comment by harshad16** [comment]
> as `sentry_dsn` is removed from the secrets, it will not be injected as an env var in deployments, and therefore thoth.logging will not send to sentry. correct?

as the value of `sentry_dsn` is removed, the env var SENTRY_DSN would fail in filter condition here
https://github.com/thoth-station/common/blob/48e0bea82abccc4de312b193dd8771af7b8d4bf1/thoth/common/logging.py#L301
and would be noted as turned off https://github.com/thoth-station/common/blob/48e0bea82abccc4de312b193dd8771af7b8d4bf1/thoth/common/logging.py#L340

**Pull request merged**
