### PR TITLE
Reduce workflows to avoid Kafka limit for messages (Data Driven Engineering)

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/thoth-application/issues/602

Reason:
Screenshot from 2020-11-20 20-40-54

### CODE REVIEW

**Comment by KPostOffice** [comment]
@pacospace I think this is happening because of a missing image

**Comment by pacospace** [comment]
> @pacospace I think this is happening because of a missing image

so shall we remove the solver from solver list? so at least the system keeps learning until the image is created.. I don't see it on quay. WDYT?

**Comment by pacospace** [comment]
> > @pacospace I think this is happening because of a missing image
> 
> so shall we remove the solver from solver list? so at least the system keeps learning until the image is created.. I don't see it on quay. WDYT?

@KPostOffice all image for solver seems to be present actually: https://github.com/thoth-station/thoth-application/blob/4ac9703cee0da6b96657486925988f0ff4f47fb1/core/overlays/stage/common/configmaps.yaml#L38, not sure where `ubi-8-py38` is coming from

**Comment by goern** [comment]
what do we do with this PR?

**Comment by pacospace** [comment]
> what do we do with this PR?

We can close it for now, it appears once removed those workflows all went back to normal.

**Comment by harshad16** [comment]
The graph-refresh run with additional solvers is overwhelming the workflow in middletier-stage.
graph-refresh

will be merging this, please feel free to open an issue. 
/approve

**Comment by pacospace** [comment]
> The graph-refresh run with additional solvers is overwhelming the workflow in middletier-stage.
> graph-refresh
> 
> will be merging this, please feel free to open an issue.
> /approve

that graph is from ocp4-stage but this PR reduced the one for ocp-stage, we need to open new one for that :)

**Comment by harshad16** [comment]
> that graph is from ocp4-stage but this PR reduced the one for ocp-stage, we need to open new one for that :)
as the change is in the base, this would reduce workflows accordingly in both clusters.

**Comment by pacospace** [comment]
> > that graph is from ocp4-stage but this PR reduced the one for ocp-stage, we need to open new one for that :)
> 
> as the change is in the base, this would reduce workflows accordingly in both clusters.

right, thanks Harsad!! :rocket:

**Pull request merged**
