### PR TITLE
Feature/merge workflow

### PR DESCRIPTION
**Pull request by xtuchyna**
## Related Issues and Dependencies
Related to #1835 

## Does this require new deployment ?

- [X] Deployment for Test and Stage `AICoE/aicoe-cd` and Prod `operate-first/argocd-apps`.

## Description
Add a new type of workflow that is not limited by parallelism and is specifically chosen for merge action

### CODE REVIEW

**Comment by xtuchyna** [comment]
But I am not sure if this does not introduce redundance? @pacospace @harshad16 
However, I am not aware of any solution other than this.

**Comment by xtuchyna** [comment]
Closes #1835

**Review by harshad16 — COMMENTED** [review]
we can try it out
/lgtm
PTAL @pacospace

**Comment by pacospace** [comment]
> But I am not sure if this does not introduce redundance? @pacospace @harshad16
> However, I am not aware of any solution other than this.

What do you mean by redundance @xtuchyna ?

**Comment by goern** [comment]
what is the status of this issue?

**Comment by goern** [comment]
ping

**Comment by xtuchyna** [comment]
> > But I am not sure if this does not introduce redundance? @pacospace @harshad16
> > However, I am not aware of any solution other than this.
> 
> What do you mean by redundance @xtuchyna ?

@pacospace because we would end up in having two workflow templates, very similar to each other

**Comment by harshad16** [comment]
Thanks for the works
Merging :+1: 
/lgtm
/approve

**Pull request merged**
