### PR TITLE
Enable preparing environment in adviser container

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
Related: https://github.com/thoth-station/thoth-application/pull/912/

@harshad16 With this change we will be able to test preparing inputs for adviser in test environment. All the changes are compatible with older releases. I'll make sure the adviser works as expected, relevant files are prepared for adviser container and we can switch changes on in messaging. If this will be better to handle just in test environment by copying manifest files, just let me know.

**Review by harshad16 — COMMENTED** [review]
/lgtm
As this is just addition, this wont have any breaking effects on existing systems.

**Comment by fridex** [comment]
> /lgtm
> As this is just addition, this wont have any breaking effects on existing systems.

Can we have changes in? I'll test it and make corresponding changes in messaging.

**Review by harshad16 — COMMENTED** [review]
/approve
this can go in.

**Pull request merged**
