### PR TITLE
Bump nepthys version in ocp to 0.2.0

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/hold

until https://quay.io/repository/thoth-station/nepthys?tag=latest&tab=tags

**Comment by fridex** [comment]
Related:
* https://github.com/thoth-station/nepthys/issues/31
* https://github.com/thoth-station/nepthys/pull/32

**Comment by fridex** [comment]
The container image is not showing up, CC @harshad16

**Comment by harshad16** [comment]
> The container image is not showing up, CC @harshad16

The aicoe-ci is running many jobs, this would be complete in short time, i will try to reduce some workload
also this pr is not needed as after nepthys image is build the ci itself will update the imagestream 
https://github.com/thoth-station/nepthys/blob/ffc13335777f7b99a35eaadf28bd8bab6b47dca2/.aicoe-ci.yaml#L14

**Comment by fridex** [comment]
> > The container image is not showing up, CC @harshad16
> 
> The aicoe-ci is running many jobs, this would be complete in short time, i will try to reduce some workload
> also this pr is not needed as after nepthys image is build the ci itself will update the imagestream
> https://github.com/thoth-station/nepthys/blob/ffc13335777f7b99a35eaadf28bd8bab6b47dca2/.aicoe-ci.yaml#L14

Awesome! I'll close it in that case. Thanks! :+1:

**Comment by harshad16** [comment]
the build pipeline , building nepthys had issue on build. 
using this pr to bump the version.

**Review by harshad16 — APPROVED** [review]
thanks :100:

**Pull request merged**
