### PR TITLE
Add solver for ubi8 and python 3.8 to configmap

### PR DESCRIPTION
**Pull request by mayaCostantini**
## Related Issues and Dependencies

Related to https://github.com/thoth-station/adviser/issues/2295

### CODE REVIEW

**Comment by harshad16** [comment]
/hold

@fridex , i was under the impression, that we were not distinguishing between ubi8 and rhel8 , please provide your ack via a lgtm or approved.

@mayaCostantini , please add link in the description for this solver and its images.

**Comment by fridex** [comment]
See https://github.com/thoth-station/adviser/issues/2295#issuecomment-1061427660 It looks like we have a bug in adviser. We do not provide ubi solvers directly.

**Comment by mayaCostantini** [comment]
@fridex thanks for finding the issue 👍🏻 
Can I close this PR?

**Comment by fridex** [comment]
Yes, I think the PR can be closed 👍🏻 thanks for digging into this.

**Pull request closed without merging**
