### PR TITLE
Bumped kebechet in test

### PR DESCRIPTION
**Pull request by saisankargochhayat**
## Related Issues and Dependencies
Wait till quay gets image - https://quay.io/repository/thoth-station/kebechet-job?tab=tags
Related - https://github.com/thoth-station/kebechet/pull/649

### CODE REVIEW

**Comment by saisankargochhayat** [comment]
@harshad16 could you please look at this image not being released?

**Review by pacospace — COMMENTED** [review]
isn't test supposed to be updated automatically?

**Comment by pacospace** [comment]
> > isn't test supposed to be updated automatically?
> 
> It stays the same even if the image is pushed, is there a way to do it automatically?

No I mean Tekton should do that, @harshad16 right? 

I can approve it for now, but maybe better to check why that is not done automatically also

**Comment by harshad16** [comment]
This is not needed, test imagestream are automatically set by the pipeline,

**Comment by harshad16** [comment]
/unhold
there seems to be issue from pipeline side.
the image is however available, i will merge this. 
/approve

**Pull request merged**
