### PR TITLE
Reduce CPU used by adviser on AWS prod

### PR DESCRIPTION
**Pull request by fridex**
## Description

Reduce CPU allocated per adviser run. Adviser uses 2 processes, one is CPU expensive, the other one is not that CPU expensive. 2.5 CPU look too much to allocate per an adviser run.

### CODE REVIEW

**Comment by fridex** [comment]
/assign @harshad16 

Do you have some metrics on this? I think 2.5 CPU is too much to allocate in this case.

**Comment by harshad16** [comment]
> Do you have some metrics on this? I think 2.5 CPU is too much to allocate in this case.

we don't have direct metrics dashboard in grafana
however if when user executes an advisor run, we can see the CPU metrics like this:
https://console-openshift-console.apps.balrog.aws.operate-first.cloud/monitoring/query-browser?query0=sum%28kube_pod_resource_limit%7Bresource%3D%27cpu%27%2Cpod%3D%27adviser-220303140706-cdd2fa9faf996ade-1132623225%27%2Cnamespace%3D%27thoth-backend-prod%27%7D%29&query1=sum%28kube_pod_resource_request%7Bresource%3D%27cpu%27%2Cpod%3D%27adviser-220303140706-cdd2fa9faf996ade-1132623225%27%2Cnamespace%3D%27thoth-backend-prod%27%7D%29+BY+%28pod%2C+namespace%29
it seems like it utilize or at least touch 2.5m CPU

**Comment by harshad16** [comment]
Interesting find ,cpu is not being used much 
however memory is going to oom for stack like this: https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/Pipfile
adviser-run

**Comment by goern** [comment]
@fridex just out of curiosity, can we correlate the incr in memory usage with the source code allocating the memory?

**Comment by fridex** [comment]
@goern Memory management should be improved with the recent changes - https://github.com/thoth-station/thoth-application/issues/2393#issuecomment-1054582150 The changes should be part of the next release. We were not observing any OOM in the stage environment with the linked change.

@harshad16 I would expect CPU to be used in later phases of the resolution process when the adviser does not talk to the database that much and rather uses cached results. Given the implementation, I would be very surprised if the implementation would use more than 1.5 CPU - we spawn two processes, one just makes sure proper memory management is done and controls child (ex. when the CPU time exceeds).

**Review by harshad16 — APPROVED** [review]
lgtm
thanks :100:

**Comment by goern** [comment]
> @fridex just out of curiosity, can we correlate the incr in memory usage with the source code allocating the memory?

I was more wondering if we are able to link both: metrics and source code.

**Pull request merged**
