### PR TITLE
include production manifest files

### PR DESCRIPTION
**Pull request by harshad16**
include production manifest files
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

## Environment

- [x] Pull Requests added content to the Prod environment

### CODE REVIEW

**Review by fridex — COMMENTED** [review]
:eyes: :partying_face:

**Comment by goern** [comment]
Shall we call the overlays for production "ocp4-psi" and "moc-kaizen"? Would we have deployment_names with the same values?

**Comment by harshad16** [comment]
> Shall we call the overlays for production "ocp4-psi" and "moc-kaizen"? Would we have deployment_names with the same values?
Good questions, we could have these name for the overlays.

**Comment by harshad16** [comment]
this is ready for merging 
if we would like to change in the overlays names, i have no personal objection to it.
@goern  @fridex  @pacospace

**Comment by fridex** [comment]
> if we would like to change in the overlays names, i have no personal objection to it.

Do we want to have one just one "`prod`" or do we plan to differentiate more?

**Comment by fridex** [comment]
> > if we would like to change in the overlays names, i have no personal objection to it.
> 
> Do we want to have one just one "`prod`" or do we plan to differentiate more?

This was also to @goern comment in https://github.com/thoth-station/thoth-application/pull/491#issuecomment-699961871. What I meant - one "prod" deployment and others would be prod-like deployments in different clusters?

**Comment by harshad16** [comment]
> This was also to @goern comment in [#491 (comment)](https://github.com/thoth-station/thoth-application/pull/491#issuecomment-699961871). What I meant - one "prod" deployment and others would be prod-like deployments in different clusters?

production environment, sharing similar type of cluster based evnironments(ex, ceph, prometheus) can still use one overlays.
we could just have different overalys in core and amun, as they have the configmap and secrets sets for deployment name as such.

core overlays - ocp-prod, ocp4-prod, ...
other application - prod.

however when we change cluster, we have to handle rolebinding based on cluster requirements, some application has rolebinding for clusterroles which need modification.


Either we can have different overlays in all apps for consistency, or different overlays only in required applications like(core, amun, etc)

**Pull request merged**
