### PR TITLE
Bump management-api to v0.6.3 in stage

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
Let's wait until https://github.com/thoth-station/management-api/issues/539 gets released.

**Review by pacospace — APPROVED** [review]

**Comment by goern** [comment]
I manually triggered a release of v0.6.3 again...

**Comment by goern** [comment]
hmm. it fails with
```
Collecting thoth-common==0.17.0
  Downloading thoth_common-0.17.0-py3-none-any.whl (36 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    thoth-common==0.17.0 from https://files.pythonhosted.org/packages/c0/10/e163a789a7de2ffd699abc9735d7dfe1249be501e4b6f1ed5902c7b46700/thoth_common-0.17.0-py3-none-any.whl#sha256=e7d517654e42dd0c29a1d9af51fcdb0d7708d206768c4ec3dfbcd582c0b2e7cc (from -r /tmp/requirements_micropipenv-h3dwd3y0.txt (line 2)):
        Expected sha256 08f5942d54e85cce69067f6e4b3f07f079ef273b2b09ae8df711d8228ec56b2b
        Expected     or 7ee03535ccc369d822817c9ce62c7b3ffee37632fd10425d07f646012d7ee60d
             Got        e7d517654e42dd0c29a1d9af51fcdb0d7708d206768c4ec3dfbcd582c0b2e7cc

Failed to install requirements, dependency 'thoth-common' could not be installed
```

see http://tekton-dashboard-tekton-pipelines.apps.thoth01.lab.upshift.rdu2.redhat.com/#/namespaces/thoth-ci/pipelineruns/tag-release-28wdp

**Comment by fridex** [comment]
> hmm. it fails with
> 
> ```
> Collecting thoth-common==0.17.0
>   Downloading thoth_common-0.17.0-py3-none-any.whl (36 kB)
> ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
>     thoth-common==0.17.0 from https://files.pythonhosted.org/packages/c0/10/e163a789a7de2ffd699abc9735d7dfe1249be501e4b6f1ed5902c7b46700/thoth_common-0.17.0-py3-none-any.whl#sha256=e7d517654e42dd0c29a1d9af51fcdb0d7708d206768c4ec3dfbcd582c0b2e7cc (from -r /tmp/requirements_micropipenv-h3dwd3y0.txt (line 2)):
>         Expected sha256 08f5942d54e85cce69067f6e4b3f07f079ef273b2b09ae8df711d8228ec56b2b
>         Expected     or 7ee03535ccc369d822817c9ce62c7b3ffee37632fd10425d07f646012d7ee60d
>              Got        e7d517654e42dd0c29a1d9af51fcdb0d7708d206768c4ec3dfbcd582c0b2e7cc
> 
> Failed to install requirements, dependency 'thoth-common' could not be installed
> ```
> 
> see http://tekton-dashboard-tekton-pipelines.apps.thoth01.lab.upshift.rdu2.redhat.com/#/namespaces/thoth-ci/pipelineruns/tag-release-28wdp

The fix should be available in management-api repo. I've triggered a new release in https://github.com/thoth-station/management-api/issues/545 thus closing this issue.

**Pull request closed without merging**
