### PR TITLE
add new workflow for graph-sync

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

https://github.com/thoth-station/thoth-application/issues/398

## This introduces a breaking change

- [ ] Yes
- [x] No

## Test or Stage Environment

- [ ] Pull Requests added content to STAGE environment
- [ ] Pull Requests to `AICoE/aicoe-cd` has been opened: 

## This Pull Request implements

We want to be able to schedule graph-sync independently so that we can trigger it using thoth-common

## Description

I added a new workflow template which takes the document ID and force sync as parameters and works the exact same as the current template save the fact that it pulls the document from ceph rather than from a local directory.

I then also added a openshift template that will be used in thoth.common to schedule graph syncs specifically when triggered by amun `InspectionCompleted` messages

### CODE REVIEW

**Review by pacospace — COMMENTED** [review]
lgtm

**Comment by KPostOffice** [comment]
@goern

**Review by harshad16 — APPROVED** [review]
thanks, let's get this in.

**Pull request merged**
