### PR TITLE
Bump integration-tests to v0.8.3

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/integration-tests/issues/202

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... until available https://quay.io/repository/thoth-station/integration-tests?tab=tags

**Comment by fridex** [comment]
> ... until available https://quay.io/repository/thoth-station/integration-tests?tab=tags

/unhold

The built image is available.

**Comment by goern** [comment]
/hold

Shall we bounce the image tag used in zero-prod too?

/approve

**Comment by fridex** [comment]
> Shall we bounce the image tag used in zero-prod too?

The imagestreamtag used for testing prod should live in `cnv-prod-ocp4-stage` overlay which has the version bump already included in this PR.

**Comment by goern** [comment]
ja, I thought about bouncing https://github.com/thoth-station/thoth-application/blob/master/prow/overlays/cnv-prod/config.yaml#L306

**Comment by fridex** [comment]
> prow/overlays/cnv-prod/config.yaml#L306

Updated in d284eb01

**Comment by goern** [comment]
thanks a lot! :100: 
/approve

**Pull request merged**
