### PR TITLE
Bump user-api to v0.34.2 in prod

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/storages/pull/2578

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... until available https://quay.io/repository/thoth-station/user-api?tab=tags

**Comment by goern** [comment]
interesting... user-api is based on quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.32.0 [srcRef](https://github.com/thoth-station/user-api/blob/master/.aicoe-ci.yaml#L4) that container images has 0 vulnerabilities ([see quay](https://quay.io/repository/thoth-station/s2i-thoth-ubi8-py38/manifest/sha256:f4a6004808429dfa298b493d9acd04490ec4d5b1694794fcbf82349f114c5fd3?tab=vulnerabilities)), the user-api container image has [7 High-level vulnerabilities](https://quay.io/repository/thoth-station/user-api/manifest/sha256:da4deb819740b293aa8f6c671b7004289ac3ffaca7f7fc4e14a2d0fbaa40626d?tab=vulnerabilities) all trace back to [RHSA-2021:3816](https://access.redhat.com/errata/RHSA-2021:3816). 

1. how did that end up in user-api container image?

**Comment by goern** [comment]
maybe this is a thing? https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/trivy-scanner I didn't find any similar task for clair/quay.io

**Comment by goern** [comment]
> user-api is based on quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.32.0 [srcRef](https://github.com/thoth-station/user-api/blob/master/.aicoe-ci.yaml#L4) that container images has 0 vulnerabilities

my fault, v0.32.0 has 7 vuls on quay, v0.32.2 has 0

**Comment by codificat** [comment]
/close 
in favour of #2316

**Pull request closed without merging**
