### PR TITLE
synchronous manifest file of ocp4 stage with ocp stage

### PR DESCRIPTION
**Pull request by harshad16**
## Related Issues and Dependencies

Related-to: https://github.com/AICoE/aicoe-cd/pull/178

## This introduces a breaking change

- [x] Yes
- [ ] No

## Test or Stage Environment

- [x] Pull Requests added content to OCP4-STAGE environment
- [x] Pull Requests to `AICoE/aicoe-cd` has been opened: 

## This Pull Request implements

synchronous manifest file of ocp4 stage with ocp stage
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Review by pacospace — COMMENTED** [review]
lgtm

**Comment by harshad16** [comment]
Related-to: #504

**Pull request merged**
