### PR TITLE
Bump investigator stage to v0.9.0

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Comment by harshad16** [comment]
/hold 

was this test in the test env?
as the v0.9.0 had new feature added.

**Review by fridex — APPROVED** [review]
lgtm! :100:

**Comment by pacospace** [comment]
> /hold
> 
> was this test in the test env?
> as the v0.9.0 had new feature added.

I don't see issues in test environment with v0.9.0 :) and new metric is exposed. @KPostOffice something more to check?

**Comment by goern** [comment]
Shall we put all the individuals that we required to approve deployment of a certain component into an OWNERS file per component? This way Prow would only ask these people for review, and we would cleary see who has no objections to deploy to stage.

We could have each PR to a stage directory start with /hold, and the last of the reviewers is required to /unhold it. This would be a "required but not enforced" review by all component owners.

**Comment by harshad16** [comment]
/unhold

saw an issue with v0.8.2 in stage https://github.com/thoth-station/investigator/issues/435
would like to move this v0.9.0 to **stage**, as it seems stable in the test cluster.

**Review by harshad16 — APPROVED** [review]
lgtm , thanks :+1:

**Pull request merged**
