### PR TITLE
add new workflow helper to update kebechet installation details

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

Depends on: https://github.com/thoth-station/workflow-helpers/pull/223

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

add new workflow helpers tasks for updating kebechet installation at the beginning kebechet workflow in test

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
lgtm
these are not added to the kustomize file, is that intended?

**Comment by KPostOffice** [comment]
@harshad16  PTAL

**Comment by harshad16** [comment]
/approve
/unhold 

lgtm , this can go in.

**Pull request merged**
