### PR TITLE
add CREATE_KNOWLEDGE flag

### PR DESCRIPTION
**Pull request by xtuchyna**
## Related Issues and Dependencies
Related to https://github.com/thoth-station/thoth-application/issues/1835
and https://github.com/thoth-station/mi-scheduler/pull/213

## Does this require new deployment ?

- [x] Deployment for Test and Stage `AICoE/aicoe-cd` and Prod `operate-first/argocd-apps`.

## Description
Adding a create_knowledge flag to the spec, resulting in new, more abstract and general type of `mi` workflow. This way, the template can be used both for merge and data workflows, without making redundant template copies. The only remaining question is, whether we can set another independent semaphor for merge workflows (or more specifically, to have semaphor only for GitHub-API-rate-limit-related workflows, and no semaphor for other workflows)

### CODE REVIEW

**Review by meile18 — APPROVED** [review]
LGTM :+1:

**Comment by harshad16** [comment]
@xtuchyna this lgtm
however this feature would requires first new mi to be released with latest common package, right ?
if not unhold.
/hold

**Comment by xtuchyna** [comment]
@harshad16 yes
is that an issue?

**Comment by xtuchyna** [comment]
@harshad16 everything is set up, so I think we can
/approve

**Comment by xtuchyna** [comment]
WDYT @fridex

**Comment by harshad16** [comment]
> everything is set up (all related PRs merged), so I think we can /approve

personally i dont think it would work, unless the mi-scheduler image is update , which contains the change
https://github.com/thoth-station/thoth-application/blob/72cd707c2ae7213eedd93c0bbc73838dc588d830/mi-scheduler/overlays/test/imagestreamtag.yaml#L24

**Pull request merged**
