### PR TITLE
Adjust adviser's memory optimizer limit

### PR DESCRIPTION
**Pull request by fridex**
## Description

It looks like we have still some memory available to fill. Activate the memory optimization later.

image

image

### CODE REVIEW

**Comment by fridex** [comment]
For future selves: adviser can suddenly do a memory consumption bump when it is aggregating results as some pipeline units are called after the actual resolution process (wraps). That's why there is left some space for the process to aggregate resolutions for users.

**Comment by mayaCostantini** [comment]
> For future selves: adviser can suddenly do a memory consumption bump when it is aggregating results as some pipeline units are called after the actual resolution process (wraps). That's why there is left some space for the process to aggregate resolutions for users.

@fridex Should we document this somewhere?

**Review by mayaCostantini — APPROVED** [review]
lgtm 💯 👍🏻

**Comment by fridex** [comment]
> > For future selves: adviser can suddenly do a memory consumption bump when it is aggregating results as some pipeline units are called after the actual resolution process (wraps). That's why there is left some space for the process to aggregate resolutions for users.
> 
> @fridex Should we document this somewhere?

Good idea, opened https://github.com/thoth-station/adviser/pull/2289 PTAL 👍🏻

**Pull request merged**
