### PR TITLE
Bump adviser to v0.49.0 in stage environment

### PR DESCRIPTION
**Pull request by fridex**
Related: https://github.com/thoth-station/adviser/issues/2218

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... let's wait for changes and a new build at https://quay.io/repository/thoth-station/adviser?tab=tags

**Comment by fridex** [comment]
The built image is available.

/assign @harshad16

**Review by harshad16 — APPROVED** [review]
lgtm
thanks :100:

**Pull request merged**
