### PR TITLE
Adjust adviser workflow tasks

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/investigator/issues/113
Depends-On: https://github.com/thoth-station/workflow-helpers/pull/155

## This introduces a breaking change

- [ ] Yes
- [x] No

## Test or Stage Environment

- [x] Pull Requests added content to STAGE environment
- [ ] Pull Requests to `AICoE/aicoe-cd` has been opened: 

## This Pull Request implements

Adjust adviser workflow tasks

### CODE REVIEW

**Comment by pacospace** [comment]
Tested successfully, we need new workflow helpers before unholding: v0.1.19

**Review by harshad16 — APPROVED** [review]
lgtm :+1:

**Pull request merged**
