### PR TITLE
remove double apps from field label scraped in Thanos for user-API in Smaug

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
## Related Issues and Dependencies

resolves  [thoth-station/thoth-application issue 2160](https://github.com/thoth-station/thoth-application/issues/2160)

## Does this require new deployment ?

- [ ] Deployment for Test and Stage `AICoE/aicoe-cd` and Prod `operate-first/argocd-apps`. No.

## Description

- Removed double apps from field label in sli-slo grafana dashboard.
- Updated config map to reflect double apps change.
- renamed overlay `moc-prod-ocp4-stage` to `moc-prod` (`ocp4-stage` overlay already exists).

### CODE REVIEW

**Comment by pacospace** [comment]
hey @Gkrumbach07 did we solve this https://github.com/thoth-station/thoth-application/issues/2160? 
Because otherwise the double apps filed is correct in the grafana dashboards.

**Comment by pacospace** [comment]
cc @Gregory-Pereira

**Comment by Gregory-Pereira** [comment]
not yet but i just found [the problem](https://github.com/thoth-station/thoth-application/pull/2043/files) : sweat_smile: .I'll have a pr out in a few minutes.

**Comment by Gregory-Pereira** [comment]
@harshad16,  does merging  [2195](https://github.com/thoth-station/thoth-application/pull/2195) mean we can unhold this?

**Review by harshad16 — CHANGES_REQUESTED** [review]
please revert the chnage on slo-reporter 
naming convention of moc-prod-ocp4-stage
it is for a reason, as we are running moc-prod workload in ocp4-stage

**Review by harshad16 — APPROVED** [review]
lgtm
thanks :100:

**Pull request merged**
