### PR TITLE
Bump adviser to v0.35.0 in stage environment

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... until available:

https://github.com/thoth-station/adviser/issues/1952
https://quay.io/repository/thoth-station/adviser?tab=tags

**Comment by goern** [comment]
/kind bug
/priority urgent-critical

@harshad16 looks like the delivery pipeline is stuck?!

**Comment by harshad16** [comment]
checked on the pipelien, it was stuck
cleared the overhead, it will be build soon.

**Review by pacospace — APPROVED** [review]

**Pull request merged**
