### PR TITLE
Add flag to optionally sync results of package-extract

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/thoth-application/issues/946

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... until all the relevant PRs get in (https://github.com/thoth-station/management-api/pull/715, https://github.com/thoth-station/messaging/pull/362, https://github.com/thoth-station/common/pull/1115). Otherwise no sync will be done.

**Review by harshad16 — APPROVED** [review]
lgtm, thanks :+1:

**Comment by fridex** [comment]
Tested in the test environment. The messaging change is not relevant for management-api as management-api directly calls openshift API to schedule the workflow. Also, the messaging change has defaults which will cause disabling graph-syncs from user-api (intentional, ok).

@harshad16 managemnet-api in version `0.14.0` is needed to bring this feature. If merged:

* package-extract results will **not** be synced from user-api (intentional)
* package-extract results will be synced when triggered from management-api **only** when management-api v.0.14.0 is brought to deployment

See https://github.com/thoth-station/thoth-application/issues/946 for more info

**Comment by fridex** [comment]
See https://github.com/thoth-station/thoth-application/pull/949#issuecomment-784038970 for more info on this when bringing this feature.

**Comment by harshad16** [comment]
/unhold
this can go in now, as we already the management-api v0.14.0 in for stage and prod. 
Related-to: 924

**Pull request merged**
